--  ============================================================================
--  MACHINE-PRODUCED ARTIFACT
--
--  Generated by The Dark Factory's `ada-verified` pipeline on 2026-05-12.
--  Inputs:  factory/inputs/{spec,planner_result,test_cases}.json
--  Reproduction notes: factory/README.md
--
--  Probe results for this run:
--    compiled=true, proved=true, component_tested=true
--    signatures fired: emit_body_spark_mode_aspect (M-25),
--                      emit_body_with_spec_identifiers (M-29)
--    winning candidate: seed=42, temp=0.8 (of N=3 sampled)
--
--  Hand-written reference implementation at ../../src/state_pension.ads
--  ============================================================================

package State_Pension with SPARK_Mode => On is
  type DWP_Subject_Id is new Natural;
  type HMRC_Subject_Id is new Natural;
  type Citizen_Subject_Id is new Natural;
  type Day_Number is range 0 .. 100_000;  -- days from 1901-01-01
  subtype Date_Of_Birth_Day is Day_Number range 19_088 .. 47_117;
  subtype Pence_Amount is Integer range 0 .. 10_000_000;
  subtype Weekly_Rate is Pence_Amount range 0 .. 100_000;
  subtype Annual_Total is Pence_Amount range 0 .. 5_200_000;
  subtype Qualifying_Years is Integer range 0 .. 80;
  Qualifying_Year_Threshold : constant Qualifying_Years := 10;
  Full_Year_Threshold       : constant Qualifying_Years := 35;
  type DWP_Record is record
    Subject : DWP_Subject_Id;
    Date_Of_Birth : Date_Of_Birth_Day;
  end record;
  type HMRC_Record is record
    Subject : HMRC_Subject_Id;
    Date_Of_Birth : Date_Of_Birth_Day;
    Qualifying_Count : Qualifying_Years;
  end record;
  type Citizen_Record is record
    Subject : Citizen_Subject_Id;
    Date_Of_Birth : Date_Of_Birth_Day;
  end record;
  type Query_Context is record
    As_Of_Date : Day_Number;
    Full_New_Weekly_Rate : Weekly_Rate;
  end record;
  function Records_Agree (DWP : DWP_Record; HMRC : HMRC_Record; Citizen : Citizen_Record) return Boolean is
    (DWP.Date_Of_Birth = HMRC.Date_Of_Birth
     and then HMRC.Date_Of_Birth = Citizen.Date_Of_Birth
     and then Natural(DWP.Subject) = Natural(HMRC.Subject)
     and then Natural(HMRC.Subject) = Natural(Citizen.Subject));
  function State_Pension_Start_Day (DoB : Date_Of_Birth_Day) return Day_Number
    with Post => State_Pension_Start_Day'Result > DoB
      and then State_Pension_Start_Day'Result - Day_Number(DoB) in 21_915 .. 25_567;
  type Decision_Reason is
    (Records_Disagree,
     Pre_State_Pension_Age,
     Below_Qualifying_Threshold,
     Pro_Rata_Entitlement,
     Full_Entitlement);
  procedure Decide (DWP : in DWP_Record;
                    HMRC : in HMRC_Record;
                    Citizen : in Citizen_Record;
                    Context : in Query_Context;
                    Weekly_Amount : out Weekly_Rate;
                    Annual_Amount : out Annual_Total;
                    Reason : out Decision_Reason)
    with Post =>
      (if Reason = Records_Disagree then
         Weekly_Amount = 0
           and Annual_Amount = 0
           and not Records_Agree(DWP, HMRC, Citizen))
        and then
      (if Reason = Pre_State_Pension_Age then
         Weekly_Amount = 0
           and Annual_Amount = 0
           and Records_Agree(DWP, HMRC, Citizen)
           and Context.As_Of_Date < State_Pension_Start_Day(DWP.Date_Of_Birth))
        and then
      (if Reason = Below_Qualifying_Threshold then
         Weekly_Amount = 0
           and Annual_Amount = 0
           and Records_Agree(DWP, HMRC, Citizen)
           and Context.As_Of_Date >= State_Pension_Start_Day(DWP.Date_Of_Birth)
           and HMRC.Qualifying_Count < Qualifying_Year_Threshold)
        and then
      (if Reason = Pro_Rata_Entitlement then
         Records_Agree(DWP, HMRC, Citizen)
           and Context.As_Of_Date >= State_Pension_Start_Day(DWP.Date_Of_Birth)
           and HMRC.Qualifying_Count >= Qualifying_Year_Threshold
           and HMRC.Qualifying_Count < Full_Year_Threshold
           and Weekly_Amount = Context.Full_New_Weekly_Rate * HMRC.Qualifying_Count / Full_Year_Threshold)
        and then
      (if Reason = Full_Entitlement then
         Records_Agree(DWP, HMRC, Citizen)
           and Context.As_Of_Date >= State_Pension_Start_Day(DWP.Date_Of_Birth)
           and HMRC.Qualifying_Count >= Full_Year_Threshold
           and Weekly_Amount = Context.Full_New_Weekly_Rate)
        and then
      Annual_Amount = Weekly_Amount * 52;
end State_Pension;
