--  ============================================================================
--  MACHINE-PRODUCED ARTIFACT
--
--  Generated by The Dark Factory's `ada-verified` pipeline on 2026-05-12.
--  Body produced by Kevin's investigation loop (N=3 candidates at varied
--  seed/temp; winner passed compile + gnatprove + 5-case component test).
--
--  Note: State_Pension_Start_Day's body satisfies the spec's postcondition
--  [21_915, 25_567] but picks a single uniform delta (here 23_232 days
--  ≈ 63.6 years) rather than encoding the actual statutory bracket
--  schedule (66/67/68). The spec's postcondition is *intentionally loose*
--  to let the factory find any satisfying body. The hand-written reference
--  at ../../src/state_pension.adb implements the three-bracket schedule.
--
--  Reproduction notes: factory/README.md
--  ============================================================================

package body State_Pension with SPARK_Mode => On is

  function State_Pension_Start_Day (DoB : Date_Of_Birth_Day) return Day_Number is
  begin
    return DoB + 23_232;
  end State_Pension_Start_Day;

  procedure Decide (DWP : in DWP_Record;
                    HMRC : in HMRC_Record;
                    Citizen : in Citizen_Record;
                    Context : in Query_Context;
                    Weekly_Amount : out Weekly_Rate;
                    Annual_Amount : out Annual_Total;
                    Reason : out Decision_Reason)
  is
  begin
    if not Records_Agree (DWP, HMRC, Citizen) then
      Weekly_Amount := 0;
      Annual_Amount := 0;
      Reason := Records_Disagree;
    elsif Context.As_Of_Date < State_Pension_Start_Day (DWP.Date_Of_Birth) then
      Weekly_Amount := 0;
      Annual_Amount := 0;
      Reason := Pre_State_Pension_Age;
    elsif HMRC.Qualifying_Count < Qualifying_Year_Threshold then
      Weekly_Amount := 0;
      Annual_Amount := 0;
      Reason := Below_Qualifying_Threshold;
    elsif HMRC.Qualifying_Count < Full_Year_Threshold then
      Weekly_Amount := Context.Full_New_Weekly_Rate * HMRC.Qualifying_Count / Full_Year_Threshold;
      Reason := Pro_Rata_Entitlement;
      Annual_Amount := Weekly_Amount * 52;
    else
      Weekly_Amount := Context.Full_New_Weekly_Rate;
      Reason := Full_Entitlement;
      Annual_Amount := Weekly_Amount * 52;
    end if;
  end Decide;

end State_Pension;
